# -*- coding: utf-8 -*-
"""XGB.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oeMW9ErAHF-XF7F7tHKVnGnOOW4eC2TE
"""

# # 🩺 Diabetes Prediction Model (XGBoost)

!pip install xgboost -q

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
import xgboost as xgb
import joblib
import json

# ## 1. Load Data

from google.colab import files

print("Please upload your CSV file (Diab_pyth_data_clean.csv):")
uploaded = files.upload()

filename = list(uploaded.keys())[0]
df = pd.read_csv(filename)

print(f"✅ Data loaded. Shape: {df.shape}")
df.head()

# ## 2. Data Preparation

target_map = {'Normal': 0, 'Prediabetes': 1, 'Diabetes': 2}
df['target'] = df['diabetes_status'].map(target_map)

X = df.drop(columns=['diabetes_status', 'target'])
y = df['target']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# ## 3. Preprocessing Pipeline

numeric_cols = X.select_dtypes(include=['int64', 'float64']).columns.tolist()
categorical_cols = X.select_dtypes(include=['object']).columns.tolist()

numeric_transformer = StandardScaler()
categorical_transformer = OneHotEncoder(handle_unknown='ignore', sparse_output=False)

preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numeric_cols),
        ('cat', categorical_transformer, categorical_cols)
    ])

# ## 4. Build XGBoost Model with Hyperparameter Tuning

xgb_model = xgb.XGBClassifier(
    random_state=42,
    eval_metric='mlogloss'
)

pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', xgb_model)
])

param_grid = {
    'classifier__n_estimators': [100, 200],
    'classifier__max_depth': [4, 6, 8],
    'classifier__learning_rate': [0.05, 0.1],
    'classifier__subsample': [0.8, 1.0],
    'classifier__colsample_bytree': [0.8, 1.0]
}

grid_search = GridSearchCV(
    pipeline, param_grid, cv=3, scoring='accuracy', n_jobs=-1, verbose=1
)
grid_search.fit(X_train, y_train)

print(f"\n✅ Best parameters: {grid_search.best_params_}")
print(f"Best CV accuracy: {grid_search.best_score_:.4f}")

best_model = grid_search.best_estimator_

# ## 5. Evaluation on Test Set

y_pred = best_model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)

print(f"\n🎯 Test Accuracy: {accuracy:.4f}\n")
print("Classification Report:")
print(classification_report(y_test, y_pred, target_names=['Normal', 'Prediabetes', 'Diabetes']))

cm = confusion_matrix(y_test, y_pred)
plt.figure(figsize=(6,5))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=['Normal', 'Prediabetes', 'Diabetes'],
            yticklabels=['Normal', 'Prediabetes', 'Diabetes'])
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix - XGBoost')
plt.show()

# ## 6. Feature Importance (XGBoost)

preprocessor_fitted = best_model.named_steps['preprocessor']
numeric_features = numeric_cols
categorical_encoder = preprocessor_fitted.named_transformers_['cat']
categorical_features = categorical_encoder.get_feature_names_out(categorical_cols)
all_features = np.concatenate([numeric_features, categorical_features])

xgb_clf = best_model.named_steps['classifier']
importances = xgb_clf.feature_importances_

indices = np.argsort(importances)[::-1][:20]
plt.figure(figsize=(10,6))
plt.title('Top 20 Feature Importances (XGBoost)')
plt.barh(range(len(indices)), importances[indices], align='center')
plt.yticks(range(len(indices)), [all_features[i] for i in indices])
plt.gca().invert_yaxis()
plt.xlabel('Importance')
plt.tight_layout()
plt.show()

# ## 7. Save the Model as .pkl (Internal)

joblib.dump(best_model, 'diabetes_model_xgb.pkl')
with open('target_mapping.json', 'w') as f:
    json.dump(target_map, f)

print("✅ Model saved locally as 'diabetes_model_xgb.pkl'")
print("✅ Target mapping saved as 'target_mapping.json'")

# ## 8. Quick Test (Load and Predict)

# Load the saved model and test on a few samples
loaded_model = joblib.load('diabetes_model_xgb.pkl')
sample = X_test.iloc[:3]
preds = loaded_model.predict(sample)

reverse_target_map = {v: k for k, v in target_map.items()}
pred_labels = [reverse_target_map[p] for p in preds]

print("Sample predictions:")
for i, idx in enumerate(sample.index):
    print(f"Sample {i+1} (index {idx}): {pred_labels[i]}")

# ## 9. Download the .pkl Model File to Your Computer

from google.colab import files

# Download the model
files.download('diabetes_model_xgb.pkl')
# Also download the mapping if you need it later
files.download('target_mapping.json')

print("✅ The model file and mapping have been downloaded to your local machine.")